# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

migrad_cpp <- function(par, f_R, lower, higher, control) {
    .Call('migrad_migrad_cpp', PACKAGE = 'migrad', par, f_R, lower, higher, control)
}

migrad_grad_cpp <- function(par, f_R, g_R, lower, higher, control) {
    .Call('migrad_migrad_grad_cpp', PACKAGE = 'migrad', par, f_R, g_R, lower, higher, control)
}

